// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBbiRx5QMNZ8UxRTgL-Kk2BlkcBBFvNI',
    appId: '1:505428523462:web:ed6eb3ec7890b033f29ac7',
    messagingSenderId: '505428523462',
    projectId: 'smart-workplace-1d688',
    authDomain: 'smart-workplace-1d688.firebaseapp.com',
    databaseURL: 'https://smart-workplace-1d688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-workplace-1d688.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjOUjJoOLva24dRyCidC-DVJMr7Z5cT0',
    appId: '1:505428523462:android:8b3a680279232a5af29ac7',
    messagingSenderId: '505428523462',
    projectId: 'smart-workplace-1d688',
    databaseURL: 'https://smart-workplace-1d688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-workplace-1d688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FffS2BlWr1c11AjNWa7qd1BcXDO5AOY',
    appId: '1:505428523462:ios:561c0b3fd0485ea7f29ac7',
    messagingSenderId: '505428523462',
    projectId: 'smart-workplace-1d688',
    databaseURL: 'https://smart-workplace-1d688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-workplace-1d688.firebasestorage.app',
    iosBundleId: 'com.example.smartWorkplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5FffS2BlWr1c11AjNWa7qd1BcXDO5AOY',
    appId: '1:505428523462:ios:561c0b3fd0485ea7f29ac7',
    messagingSenderId: '505428523462',
    projectId: 'smart-workplace-1d688',
    databaseURL: 'https://smart-workplace-1d688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-workplace-1d688.firebasestorage.app',
    iosBundleId: 'com.example.smartWorkplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBbiRx5QMNZ8UxRTgL-Kk2BlkcBBFvNI',
    appId: '1:505428523462:web:4bf8b0cde9db17c5f29ac7',
    messagingSenderId: '505428523462',
    projectId: 'smart-workplace-1d688',
    authDomain: 'smart-workplace-1d688.firebaseapp.com',
    databaseURL: 'https://smart-workplace-1d688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-workplace-1d688.firebasestorage.app',
  );
}
